version: '3.8'
services:
  demo-monet-petclinic:
    image: demo-monet-app
    container_name: demo-monet-app
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
    volumes:
      - ./:/app
    depends_on:
      - demo-monet-mysqlserver

  demo-monet-petclinic-prebuilt:
    image: demo-monet-app-multi-stage
    container_name: demo-monet-app-prebuilt
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
    volumes:
      - ./:/app
    depends_on:
      - demo-monet-mysqlserver

  demo-monet-mysqlserver:
    image: mysql
    container_name: demo-monet-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: